//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "passage_to_prayer_request")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub passage_id: String,
    pub prayer_request_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::passage::Entity",
        from = "Column::PassageId",
        to = "super::passage::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Passage,
    #[sea_orm(
        belongs_to = "super::prayer_request::Entity",
        from = "Column::PrayerRequestId",
        to = "super::prayer_request::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PrayerRequest,
}

impl Related<super::passage::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Passage.def()
    }
}

impl Related<super::prayer_request::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PrayerRequest.def()
    }
}
